@startuml

skinparam ParticipantFontStyle bold
skinparam DatabaseFontStyle bold
skinparam CollectionsFontStyle bold
skinparam BackgroundColor White
skinparam TitleFontSize 25
skinparam TitleFontStyle bold
autonumber


title Project UML Diagram


database "YFinance API" #3D8B7F
participant "Data Handler" #White
database "Local data" #SteelBlue
participant Computation #White
participant Prediction #White
participant Grapher #White
collections Plots #GoldenRod
collections Logs #GoldenRod


group Data Fetching
"Data Handler"->"YFinance API": Send query to API
activate "Data Handler" #LightSlateGrey
activate "YFinance API" #LightSlateGrey
"YFinance API"->"Data Handler": Return stock data
deactivate "YFinance API"
end


autonumber stop
"Data Handler"-->>Logs
autonumber resume


group Data Pre-processing
"Data Handler"->"Data Handler": Filter data
"Data Handler"->"Data Handler": Reduce data
"Data Handler"->"Local data": Out pre-processed \n data to CSV
deactivate "Data Handler"
activate "Local data" #LightSlateGrey
end


autonumber stop
"Data Handler"-->>Logs
autonumber resume


"Local data"->Computation: Load data
group Data Computing
deactivate "Local data"
activate Computation #LightSlateGrey
Computation->Computation: Compute stock \n profitability
Computation->Computation: Compute portfolio \n Sharpe Ratio
end
Computation->"Local data": Out computed data \n to JSON
deactivate Computation
activate "Local data" #LightSlateGrey



autonumber stop
Computation-->>Logs
autonumber resume


"Local data"->Prediction: Load data
group Data Prediction
deactivate "Local data"
activate Prediction #LightSlateGrey
Prediction->Prediction: Predict current\n portfolio profitability
Prediction->Prediction: Predict other stocks \n profitability
Prediction->Prediction: Recommend \n trading action
end
Prediction->"Local data": Out predicted data \n to JSON
deactivate Prediction
activate "Local data" #LightSlateGrey


autonumber stop
Prediction-->>Logs
autonumber resume


"Local data"->Grapher: Load data
deactivate "Local data"
group Data Visualisation
activate Grapher #LightSlateGrey
Grapher->Plots: Plot portfolio \n distribution
Grapher->Plots: Plot candlestick graph \n for portfolio stocks
end
deactivate Grapher


autonumber stop
Grapher-->>Logs
autonumber resume


@enduml

@startuml
colors SteelBlue
@enduml

@startuml
colors 3D8B7F
@enduml