@startuml

skinparam ParticipantFontStyle bold
skinparam DatabaseFontStyle bold
skinparam CollectionsFontStyle bold
skinparam BackgroundColor White
skinparam TitleFontSize 25
skinparam TitleFontStyle bold
autonumber


title Project UML Diagram


database "YFinance API" #3D8B7F
database "Local data" #SteelBlue
participant Config #White
participant Computation #White
participant Prediction #White
participant Decision #White
collections Plots #GoldenRod


group Portfolio initialisation
activate Computation #LightSlateGrey
Computation <-> "YFinance API": Fetch market data
Computation <-> Config: Load \nconfiguration
Computation -> Computation: Compute most \nperforming stocks
Computation -> Computation: Solve constrained\noptimisation \nproblem
Computation -> "Local data": Output currrent \nportfolio to JSON
Plots <-> Computation: Plot current \nportfolio
deactivate Computation
end


group Portfolio evaluation
Prediction <-> "Local data": Load current portfolio data
activate Prediction #LightSlateGrey
Prediction -> Prediction: Predict portfolio \nstock prices
alt #LightGreen Bullish portfolio
    Prediction -->Prediction: Return current\nPortfolio
else #Pink Bearish stocks in portfolio
    Prediction -> Prediction: Predict other\nstocks
    Prediction -> Prediction: Suggest new\ninvestment
    Prediction -> "Local data": Output suggestion to JSON
end
deactivate Prediction
end


group Decision-making
Decision <-> "Local data": Load investment suggestion
activate Decision #LightSlateGrey
alt #LightGreen Act on suggestion
    Decision -> Decision: Modify current \nportfolio
    Decision -> "Local data": Output new portfolio to JSON
    Plots <-> Decision: Plot new \nportfolio
else #Pink Stay on current portfolio
    Decision --> Decision: Return current\nportfolio
end
deactivate Decision
end
@enduml

@startuml
colors SteelBlue
@enduml

@startuml
colors 3D8B7F
@enduml